// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbT5fnEthYEvVwS9hw28uwubIBf62b5s',
    appId: '1:792672749617:web:7cb730e6966cfb6f3ced10',
    messagingSenderId: '792672749617',
    projectId: 'asroo-chop-getxx',
    authDomain: 'asroo-chop-getxx.firebaseapp.com',
    storageBucket: 'asroo-chop-getxx.appspot.com',
    measurementId: 'G-8L55YMF833',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYmc2I5p8JDLmb7moSkOD1p3OYDKOmGA',
    appId: '1:792672749617:android:1d12a7f8558271a53ced10',
    messagingSenderId: '792672749617',
    projectId: 'asroo-chop-getxx',
    storageBucket: 'asroo-chop-getxx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB31cT-LpjtJQboQ-p-M9PxdWg35WBuBco',
    appId: '1:792672749617:ios:cd28ba41c52069433ced10',
    messagingSenderId: '792672749617',
    projectId: 'asroo-chop-getxx',
    storageBucket: 'asroo-chop-getxx.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB31cT-LpjtJQboQ-p-M9PxdWg35WBuBco',
    appId: '1:792672749617:ios:cd28ba41c52069433ced10',
    messagingSenderId: '792672749617',
    projectId: 'asroo-chop-getxx',
    storageBucket: 'asroo-chop-getxx.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVbT5fnEthYEvVwS9hw28uwubIBf62b5s',
    appId: '1:792672749617:web:f6548a9d4da4a8db3ced10',
    messagingSenderId: '792672749617',
    projectId: 'asroo-chop-getxx',
    authDomain: 'asroo-chop-getxx.firebaseapp.com',
    storageBucket: 'asroo-chop-getxx.appspot.com',
    measurementId: 'G-V54H4HGM6Z',
  );
}
